### ISSUE TITLE
cluster-capacity support other scheduler 

### ISSUE THREAD

**Issue by ringtail** [kubernetes-sigs/cluster-capacity#105]
such as gang-scheduler and kube-batch

**Comment by aveshagarwal** [comment]
> such as gang-scheduler and kube-batch

We have not discussed about it, but that sounds like a good idea to me to have more scheduler options as part of cluster-capacity. Would you like to take it forward?

**Comment by ringtail** [comment]
@aveshagarwal I think cluster-capacity framework is the best place to wrapper these differences.

**Comment by ingvagabund** [comment]
> such as gang-scheduler and kube-batch

+1
