### ISSUE TITLE
Not able to detect the failure message for each node

### ISSUE THREAD

**Issue by peter-wangxu** [kubernetes-sigs/cluster-capacity#137]
`./cluster-capacity --kubeconfig=k8s.kubeconfig --podspec 1.yaml --verbose`
test-0 pod requirements:
	- CPU: 2
	- Memory: 4Gi

The cluster can schedule 0 instance(s) of the pod test-0.

Termination reason: Unschedulable: 0/21 nodes are available: 1 node(s) didn't find available persistent volumes to bind, 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't match pod anti-affinity rules, 1 node(s) had taint {node.k8s.test/lifecycle: offline}, that the pod didn't tolerate, 18 node(s) didn't match Pod's node affinity.

**Comment by ingvagabund** [comment]
Kube-scheduler aggregates the node reasons. Currently, there's no way to tell a failure message for a specific node.
/close
